/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capadeinterfaz;

/**
 *
 * @author Joshue
 */
import capadenegocio.UsuarioNegocio;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Image;
import java.io.File;
import java.io.InputStream;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    public Login() {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        cargarImagenDesdeRecurso("img/6.jpg", jLabel2, 480, 550); // Primera imagen
         cargarImagenDesdeRecurso("img/2.png", jLabel3, 160, 120); // Segunda imagen
        
         // Ajustar las posiciones si es necesario
        jLabel2.setBounds(0, 0, 480, 550);  // Primera imagen ocupa el espacio completo
        jLabel3.setBounds(550, 10, 160, 120); // Ajusta la posición y tamaño de la segunda imagen
      
    }
    private void cargarImagenDesdeRecurso(String rutaRecurso, JLabel label, int ancho, int alto) {
    try {
        // Cargar la imagen desde el recurso
        InputStream inputStream = getClass().getClassLoader().getResourceAsStream(rutaRecurso);
        
        if (inputStream != null) {
            // Cargar la imagen desde el InputStream
            ImageIcon icono = new ImageIcon(ImageIO.read(inputStream));
            
            // Ajustar la imagen al tamaño deseado
            Image imagen = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
            label.setIcon(new ImageIcon(imagen));

            // Ajustar el tamaño del JLabel desde código
            label.setBounds(label.getX(), label.getY(), ancho, alto); // Usa la posición que quieras

            System.out.println("✅ Imagen cargada con éxito en " + label.getText());
        } else {
            System.out.println("❌ Error: No se encontró el recurso " + rutaRecurso);
        }
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("❌ Error al cargar la imagen.");
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(457, 559));
        setPreferredSize(new java.awt.Dimension(791, 526));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 110, 250, 60);
        jLabel1.getAccessibleContext().setAccessibleName("lbltitle");

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(530, 190, 80, 16);
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(530, 210, 180, 40);

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(530, 270, 70, 16);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(530, 290, 179, 40);

        btnIngresar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setName(""); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(560, 390, 110, 40);

        btnSalir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(570, 470, 90, 30);

        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 446));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 446));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 170, 37, 16);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 50, 37, 16);

        jPanel2.setMaximumSize(new java.awt.Dimension(450, 446));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 446));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 480, 550);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(550, 10, 160, 120);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        // Obtener los valores ingresados
        // Obtener los valores ingresados
        String usuario = txtUsuario.getText();
        String password = new String(txtPassword.getPassword());

        // Instancia de la capa de negocio
        UsuarioNegocio usuarioNegocio = new UsuarioNegocio();
        
        if (usuarioNegocio.validarUsuario(usuario, password)) {
            JOptionPane.showMessageDialog(this, "Bienvenido " + usuario);
            
            // Abrir el menú principal
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
            
            // Cerrar la ventana actual
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            // Establecer el LookAndFeel de FlatLightLaf (Tema Claro)
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

        // Crear y mostrar la ventana del login
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
